######################################################################
# Automatically generated by qmake (2.01a) Wed May 13 17:25:51 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
